### ISSUE TITLE
Feedback for milestone 2

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1036#2]
High Priority, must fix: 

- [ ]  Use relative path instead of absolute path, example: ""/Users/emmarutledge/Desktop/DATA301/course-project-group_1036/data/raw/google_review_ratings.csv"
- [ ] In your task 5, the graph for your second research question (Do users who provide a high rating to theatres, tend to give parks a low rating?). Add a title/units to the axis. Also, test out ways to make the visualization easier to understand. Do you really need the bar chart and the scatter plot? Would the scatter plot be enough on its own? Is there a better way of visualizing this? 
- [ ] All the graphs in the "Compare Ratings Distribution across Food and Beverage Categories" section are unclear. What is meant by density? What are the units of the x and y axis?  It was not clear to me that the graph the x axis was the rating. Please go through those graphs and make them easier to read, and more explanations for them. I only understood what those graphs meant until I read your explanation at the end. 
- [ ] Some members of the team are missing files in their folders, your individual grades at the end of the semester will reflect this. Please add the missing work.
